var appData = {
  feature : { XID : "TEST:uuid:B5ADF718-D4C8-473F-BFAF-B86570A233DF", title : "Plastic Beach", artist : "Gorillaz" },
  audioLoop : { src : "audio/ambient.m4a", loop : true },
  numberOfPhotos : 		31,
  numberOfBookPages : 	12,
  numberOfStoryPages : 	12,
  songs : [
    { XID : "EMI:isrc:GBAYE1000001" , ls : 1 , scroll : "block" },
    { XID : "EMI:isrc:GBAYE1000004" , ls : 1 , scroll : "none"  },
    { XID : "EMI:isrc:GBAYE1000005" , ls : 1 , scroll : "none"  },
    { XID : "EMI:isrc:GBAYE1000017" , ls : 1 , scroll : "none"  },
    { XID : "EMI:isrc:GBAYE0903021" , ls : 2 , scroll : "none"  },
    { XID : "EMI:isrc:GBAYE1000006" , ls : 2 , scroll : "none"  },
    { XID : "EMI:isrc:GBAYE1000007" , ls : 1 , scroll : "none"  },
    { XID : "EMI:isrc:GBAYE1000008" , ls : 1 , scroll : "none"  },
    { XID : "EMI:isrc:GBAYE1000009" , ls : 1 , scroll : "none"  },
    { XID : "EMI:isrc:GBAYE1000010" , ls : 1 , scroll : "none"  },
    { XID : "EMI:isrc:GBAYE1000011" , ls : 1 , scroll : "none"  },
    { XID : "EMI:isrc:GBAYE1000016" , ls : 2 , scroll : "none"  },
    { XID : "EMI:isrc:GBAYE1000012" , ls : 1 , scroll : "none"  },
    { XID : "EMI:isrc:GBAYE1000013" , ls : 1 , scroll : "none"  },
    { XID : "EMI:isrc:GBAYE1000014" , ls : 1 , scroll : "none"  },
    { XID : "EMI:isrc:GBAYE1000015" , ls : 1 , scroll : "block" },
    { XID : "EMI:isrc:GBAYE1000079" , ls : 1 , scroll : "block" },
    { XID : "EMI:isrc:GBAYE1000120" , ls : 1 , scroll : "block" },
  ],
  videos : [
	{ string : "Stylo (feat. Mos Def & Bobby Womack)", 	XID : 'EMI:isrc:GB0400900183' },
    { string : "Making Of Stylo", 		src: 'gorillaz_making_stylo.m4v'},
    { string : "Orchestral Trailer", 	src: 'gorillaz_orchestral.m4v'},
	{ string : "Murdoc", 				src: 'gorillaz_murdoc_plasticbeach.m4v'},
	{ string : "2D", 					src: 'gorillaz_2d_plasticbeach.m4v'},
	{ string : "Russel", 				src: 'gorillaz_plasticbeach_russell.m4v'},
	{ string : "Rhinestone Eyes", 		src: 'gorillaz_rhinestoneeyes.m4v'},
	{ string : "Superfast Jellyfish", 	src: 'gorillaz_superfast_jellyfish.m4v'},
	{ string : "Glitter Freeze", 		src: 'gorillaz_glitter_freeze.m4v'},
	{ string : "Some Kind Of Nature", 	src: 'gorillaz_somekindofnature.m4v'},
	{ string : "To Binge", 				src: 'gorillaz_tobinge.m4v'},
	{ string : "Cloud Of Unknowing", 	src: 'gorillaz_cloudofunknowing.m4v'},
	{ string : "Reflection", 			src: 'gorillaz_reflection.m4v'},
	{ string : "Big Fog", 				src: 'gorillaz_big_fog.m4v'},
	{ string : "Subdive Dusk", 			src: 'gorillaz_subdive_dusk.m4v'},
	{ string : "Sub", 					src: 'gorillaz_sub.m4v'},
	{ string : "Underwater Rotate", 	src: 'gorillaz_underwater_rotate.m4v'},
	{ string : "Pirate Radio", 			src: 'gorillaz_pirate_radio.m4v'},
	{ string : "Orka Ripple", 			src: 'gorillaz_orka_ripple.m4v'},
	{ string : "Plane Dock", 			src: 'gorillaz_plane_dock.m4v'},
	{ string : "Night Pier Pan", 		src: 'gorillaz_night_pier_pan.m4v'},
	{ string : "Night Lighthouse", 		src: 'gorillaz_night_lighthouse.m4v'},
	{ string : "Sundeck", 				src: 'gorillaz_sundeck.m4v'},
	{ string : "Birds Eye Island", 		src: 'gorillaz_birds_eye_island.m4v'}
  ],
  extra : [
	{ directory: 'videos', prefix: 'main', items: [ 
		{ string : "Polar Bear", src: 'gorillaz_polarbear.m4v', duration: '00:11' }, 
		{ string : "Intro", src: 'gorillaz_intro_flyinginto.m4v', duration: '00:11' },
  	]}
  ],

};